try {
  throw Error("hello");
} catch(e) {
  console.log(e);
}
